### ISSUE TITLE
bug with request

### ISSUE THREAD

**Issue by Dolbager** [cloudflare-api/python-cloudflare-v4#10]
when i'am try to create new zone by example:

$ python2 example-create-zone-and-populate.py examol.biz                                                                                                                                                                     
Create zone examol.biz ...
/zones.post examol.biz - request() got an unexpected keyword argument 'json'

Python 2.7.11
system: os x 10.11

**Comment by gnowxilef** [comment]
please open this issue in https://github.com/cloudflare/python-cloudflare/issues
