### ISSUE TITLE
example-update-dynamic-dns.py not working with top level domain

### ISSUE THREAD

**Issue by IDmedia** [cloudflare-api/python-cloudflare-v4#14]
While `example-update-dynamic-dns.py foo.bar.com` works, I can't seem to get `example-update-dynamic-dns.py bar.com` to work.

I've also tried .bar.com, bar.com., but I only get: zone not found

**Comment by gnowxilef** [comment]
please open this issue in https://github.com/cloudflare/python-cloudflare/issues
