### ISSUE TITLE
CloudFlare.exceptions.CloudFlareAPIError: Method DELETE not available for that URI

### ISSUE THREAD

**Issue by holinhot** [cloudflare-api/python-cloudflare-v4#17]
I'm try delete a dns record
use 
cf.zones.dns_records.delete(r_id)

looking like not working

CloudFlare.exceptions.CloudFlareAPIError: Method DELETE not available for that URI.

**Comment by holinhot** [comment]
cf.zones.dns_records.delete(zone_id,r_id)
ok i know

**Comment by mahtin** [comment]
Yes. Correct.

Please update from [python-cloudflare](https://github.com/cloudflare/python-cloudflare) as there's more functionality there. I'll add an example for delete in there in a few days. In the meantime; look at [example_create_zone_and_populate.py ](https://github.com/cloudflare/python-cloudflare/blob/master/examples/example_create_zone_and_populate.py) for some help.

Martin

**Comment by gnowxilef** [comment]
@mahtin can you enable issues in the cloudflare repo?

**Comment by mahtin** [comment]
@gnowxilef - done! [cloudflare/python-cloudflare/issues/11](https://github.com/cloudflare/python-cloudflare/issues/11)
