### ISSUE TITLE
No way to delete DNS record with object.zones.dns_records

### ISSUE THREAD

**Issue by klausenbusk** [cloudflare-api/python-cloudflare-v4#2]
Looking though the code, it seems like object.zones.dns_records don't support deleting dns record, or get record details.
```
GET /zones/:zone_identifier/dns_records/:identifier
DELETE /zones/:zone_identifier/dns_records/:identifier
```

**Comment by gnowxilef** [comment]
i added an example of how to do so here: https://github.com/cloudflare-api/python-cloudflare-v4/wiki/Examples.

get, post, delete all support this.

**Comment by klausenbusk** [comment]
> i added an example of how to do so here: https://github.com/cloudflare-api/python-cloudflare-v4/wiki/Examples.

Didn't know I could have 2 .get (not a python expert yet!). Thanks!

**Comment by klausenbusk** [comment]
> i added an example of how to do so here: https://github.com/cloudflare-api/python-cloudflare-v4/wiki/Examples.

Hmm. So how can I delete a dns record?
`cf.zones.dns_records.get(zone_id)[0].get(dns_id)`?
